import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Ubuntu } from "next/font/google";
import { Inter } from "next/font/google";

import { LinkProvider } from "@/context/LinkListContextProvider";

const inter = Inter({ subsets: ["latin"] });

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Import the Ubuntu font
const ubuntu = Ubuntu({
  weight: ["400", "700"], // You can choose weights like '400', '700', etc.
  subsets: ["latin"], // Choose the subset(s) you'd like to include
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <LinkProvider>{children}</LinkProvider>
      </body>
    </html>
  );
}
