import type { Metadata } from "next";
import "./globals.css";
import { Ubuntu } from "next/font/google";
import { Inter } from "next/font/google";
import Providers from "@/context/providers";

const inter = Inter({ subsets: ["latin"] });

// Import the Ubuntu font
const ubuntu = Ubuntu({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased container mx-auto`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
